#!/bin/bash


for var in "$@"
do
    if [ -z $search_string ] ; then 
        search_string="https://maps.google.com/maps?q=$var"               #hl=en&safe=off&output=search&q=$var"
    else 
        search_string="$search_string+$var"
    fi
done

midori -a "$search_string"
